name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: nodenv/actions/setup-nodenv@v2

      - name: Install node-build
        run: |
          mkdir -p "$(nodenv root)"/plugins
          git clone https://github.com/nodenv/node-build.git "$(nodenv root)"/plugins/node-build

      - name: Run nodenv init
        run: |
          echo "$(nodenv root)"/shims >> $GITHUB_PATH
          echo "NODENV_SHELL=bash" >> $GITHUB_ENV
          nodenv rehash

      - name: Check node version
        run: node -v
